#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Indoctrination.Resource", IsApplication=true)]

namespace Indoctrination
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060009
			public const int btnBack = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int btnPlaySound = 2131099656;
			
			// aapt resource value: 0x7f06000d
			public const int departmentTextView = 2131099661;
			
			// aapt resource value: 0x7f060004
			public const int editText1 = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int imageView1 = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int linearLayout1 = 2131099653;
			
			// aapt resource value: 0x7f06000a
			public const int listView1 = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int nameTextView = 2131099660;
			
			// aapt resource value: 0x7f060006
			public const int numberPicker1 = 2131099654;
			
			// aapt resource value: 0x7f06000b
			public const int photoImageView = 2131099659;
			
			// aapt resource value: 0x7f060001
			public const int relativeLayout1 = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int space1 = 2131099655;
			
			// aapt resource value: 0x7f060002
			public const int textView1 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int textView2 = 2131099651;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Detail = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MenuDetail = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MenuRow = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int jensi_1 = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int jensi_2 = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int jesmi_ablemorghan = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int jesmi_abmorvarid = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int jesmi_alzaimer = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int jesmi_chaghi = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int jesmi_charbikhon = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int jesmi_diabet = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int jesmi_fesharkhon = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int jesmi_ghodadkazeb = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int jesmi_hepatit = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int jesmi_idz = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int jesmi_kamkhoni = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int jesmi_nashenavaei = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int jesmi_ofonat = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int jesmi_pestan = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int jesmi_romatism = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int jesmi_sangkolieh = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int jesmi_saratan = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int jesmi_sekte = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int jesmi_sinozit = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int jesmi_sorkhak = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int jesmi_sotaghzieh = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int jesmi_tab = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int jesmi_tanginafas = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int jesmi_varis = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int jesmi_veba = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int jesmi_zakhmmede = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int rohi_afsordegi = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int rohi_asabaniat = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int rohi_ezterab = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int rohi_shekasteshghi = 2130968607;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
